### ISSUE TITLE
Should WeatherFlowPoly be able to find the station if its on a different subnet on the same network?

### ISSUE THREAD

**Issue by TaeKwonBow** [bpaauwe/WeatherFlow#4]
If not can we configure an IP variable?

**Comment by bpaauwe** [comment]
The WeatherFlow hub doesn't send the data over a TCP/IP connection so there isn't any IP address to configure.  The data is sent using a UDP broadcast, i.e. it is sent to all/any hosts on the local network.

If your network is not configured to forward the UDP packets to other subnets, nothing on the other subnets will be able to see the packets.  If it's not possible to configure this on your network, you could use the WeatherFlowPGC version, that will get data from the WeatherFlow servers so it will work on any subnet as long as it has access to the Internet.
