### ISSUE TITLE
Two Hub Issue

### ISSUE THREAD

**Issue by macjeff** [bpaauwe/WeatherFlow#6]
I have two hubs (one for Weatherflow and one for Tempest).  Weatherflow has asked we run Tempests on another hub for now.

I cant see a way to have two hubs or two nodes so for now I am using Nodelink for my old one and your node for the Tempest.  That way I can help you with bugs.  But I can discuss too much with tempest in a public forum.  Let me know if you want to talk off of here for more info, but here is the issue.

I tried changing station ID and restarting the node and admin console but its obviously the data from the original weatherflow not tempest due to some obvious differences including the fact there is no AIR anymore so it should be blank battery.   And the temps read different as well as false lightning on tempest.   So I reset up from scratch same problems.  Then I resetup again with a different port 50223 instead of 50222.  Same issue but maybe I need to change the port on the Tempest hub but cant figure out where to do it.   

Anything you can tell me that might help would be great.

Thanks!!

**Comment by macjeff** [comment]
I asked about changing Port.  

From weatherflow ——

No, just use the serial_number to tell station-one apart from station-two for things that are common. Key off obs_air+obs_sky for the original gear versus obs_st for the Tempest for the observations.

Both the original and tempest hubs broadcast on 50222 but the serial_number and obs_whatever items in what they broadcast is enough to tell them apart.

**Comment by bpaauwe** [comment]
The polyglot weatherflow node server doesn't currently support the Tempest.  I've been field testing a Tempest for a while now and have been adding support to the node server for it. I'm testing that support now.

**Comment by macjeff** [comment]
I have had the tempest since Christmas but just now hooked it up.   I would be happy to test the nodeserver if there is a way to beta test it.

**Comment by macjeff** [comment]
Saw the tempest update.  I assume its still one hub support?   And to add tempest we just change the station ID?

**Comment by macjeff** [comment]
Opening up new issue
