### ISSUE TITLE
Debug Log Issue

### ISSUE THREAD

**Issue by macjeff** [bpaauwe/WeatherFlow#8]
Just posting here but this is actually for all your node servers and I use most of them!!!

The latest update to polisy is causing DEBUG messages in most node servers.

Another developer fixed his. 

weatherflow is the worst with pages of DEBUG now.   If you dont see this try installing a nodeserver from Jimbo.  Most of his tend to bring this out in other nodeservers for some reason.

Here is what developer said....

Just a minor thing to address the logging issue for those that update their polyglot version. The poly interface version is what set the logging to debug so I made sure to set it to error so the log won’t blow up with stuff. That’s what other nodeservers should be set to and not debug.

**Comment by jimboca** [comment]
The polyinterface has always set logging level to debug. The change was a bug fix that it now shows logging from modules you reference.

**Comment by markv58** [comment]
Fixing the logging issue did cause a tremendous amount of logging to show up. I've gone in and limited logging to ERROR in my apps to curtail the amount of logging for now and may modify further to allow the more aggressive reporting if needed.

**Comment by bpaauwe** [comment]
This isn't actually a problem with the node server(s), but a change in behavior in the infrastructure used by the node servers. 

I know how to update my node servers to somewhat workaround this issue, but there isn't a clear solution to actually fix it.

**Comment by macjeff** [comment]
still lots of debugs but will close this

**Comment by jimboca** [comment]
Update polyinterface and restart nodeserver

**Comment by jimboca** [comment]
On RPi: pip install --upgrade polyinterface --user
On Polisy: sudo -u polyglot pip install --upgrade polyinterface --user
Or just install the PythonTemplate nodeserver and it will do the upgrade for you.
