### ISSUE TITLE
ISY Node Values Go Out of Sync with Tempest

### ISSUE THREAD

**Issue by theplaceilive** [bpaauwe/WeatherFlow#9]
I've noticed the ISY node values seem to go out of sync with the actual values within my Tempest. The most recent incorrect value observed is the Illumination Lux value. Restarting the WeatherFlowPoly Node Server temporarily resolves the incorrect ISY node value but the problem returns. Thanks

**Comment by bpaauwe** [comment]
Can you provide logs when this happens?

**Comment by theplaceilive** [comment]
Here's a recent log file. The ISY node values were way off when this log was captured. The actual Tempest temperature was 80 degrees but the ISY node temperature value was 62 degrees. The ISY node value for Illumination was 0 while Tempest showed it over 49000 Lux.
 
[WeatherFlowPoly_2020-6-21_175711.txt](https://github.com/bpaauwe/WeatherFlow/files/4810338/WeatherFlowPoly_2020-6-21_175711.txt)

Really appreciate your effort and assistance.

**Comment by theplaceilive** [comment]
Here's another log file after restarting the node server. The node values appear to be correct after restarting the node server followed by re-opening the ISY Admin Console.   
[WeatherFlowPoly_2020-6-21_180517.txt](https://github.com/bpaauwe/WeatherFlow/files/4810347/WeatherFlowPoly_2020-6-21_180517.txt)

**Comment by bpaauwe** [comment]
The node server is crashing because it's not getting any pressure values from the tempest and doesn't handle that very well.  Pressure values aren't really optional and this may indicate a hardware/sensor failure.

When you restart, something in the initial query from the WeatherFlow servers is also failing. It would help to have a log with debug level logging enabled to pinpoint what.

**Comment by theplaceilive** [comment]
I looked for a debug level logging setting and can't seem to find. But here's a copy of additional logs, including the log package if that helps. I'll be glad to turn up the log level if you can tell me where that's done. Thanks
[WeatherFlowPoly_logs_2020-6-22_193119.zip](https://github.com/bpaauwe/WeatherFlow/files/4816236/WeatherFlowPoly_logs_2020-6-22_193119.zip)
[polyglot_2020-6-22_193053.txt](https://github.com/bpaauwe/WeatherFlow/files/4816237/polyglot_2020-6-22_193053.txt)

**Comment by bpaauwe** [comment]
From the main weatherflow node in the admin console, there's a button and drop down to set the log level.  If you set the level to debug, restart the node server, and just send the log for what happens during the restart it should be enough.  You can then set the log level back to something less verbose (the initial value was either error or warning, maybe off)

**Comment by theplaceilive** [comment]
Here are logs after setting to Debug in the Admin Console and restarting the node server..
[UDReport.txt](https://github.com/bpaauwe/WeatherFlow/files/4816302/UDReport.txt)
[WeatherFlowPoly_2020-6-22_205321.txt](https://github.com/bpaauwe/WeatherFlow/files/4816303/WeatherFlowPoly_2020-6-22_205321.txt)
[WeatherFlowPoly_logs_2020-6-22_205338.zip](https://github.com/bpaauwe/WeatherFlow/files/4816304/WeatherFlowPoly_logs_2020-6-22_205338.zip)

**Comment by bpaauwe** [comment]
Thanks. Looks like the error on startup was just lack of data available so not really a problem. I've pushed a change that should handle the lack of pressure values and not crash in that case any more.

**Comment by theplaceilive** [comment]
The update appears to have resolved the issue. Thanks again for all of your effort and assistance..
